force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <description>Estimation of student&apos;s efforts.</description>
    <label>Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Starting soon</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Is over</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Average_Grade__c.field-meta.xml
<CustomField>
    <fullName>Average_Grade__c</fullName>
    <description>Average grade among related enrollments.</description>
    <label>Average Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Scholarship__c.field-meta.xml
<CustomField>
    <fullName>Scholarship__c</fullName>
    <description>Type of the scholarship awarded to a student.</description>
    <label>Scholarship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Increased</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrant</fullName>
            </value>
            <value>
                <fullName>Is studying</fullName>
            </value>
            <value>
                <fullName>Academic leave</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchoolService.cls
public class SchoolService {
    
    public static void enrollStudentToClass(Id classId, Id studentId) {

        // Create class enrollment for given class and student.
        insert new class_Enrollment__c(Class__c = classId, Student__c = studentId);
    }

    public static void setGrade(Id classId, Id studentId, Integer grade) {

        // Set grade based on given class and student.
        update new class_Enrollment__c(Id = [SELECT Id FROM Class_Enrollment__C WHERE Class__r.Id = :classId AND Student__r.Id = :studentId LIMIT 1].Id, Grade__c = grade);
    }
    
    public static void setGrade(Id classEnrollmentId, Integer grade) {

        // Set grade for given class enrollment.
        update new class_Enrollment__c(Id = classEnrollmentId, Grade__c = grade);
    }

    public static void setAcademicScholarship(Id studentId) {

        // Assign academic scholarship to a given student.
        update new Student__c(Id = studentId, Scholarship__c = 'Academic');
    }

    // Calculate if the student has a scholarship by the results of the year.
    public static void recalculateScholarship(Id studentId) {

        Decimal studentAverageGrades = [SELECT Average_Grade__c FROM Student__c WHERE Id = :studentId].Average_Grade__c;
        
        // If at least one class enrollment has no 
        // grade - a scholarship cannot be assigned yet.
        if (studentAverageGrades == null || studentAverageGrades < 71){
            update new Student__c(Id = studentId, Scholarship__c = 'Unassigned');
        }
        // In order to have a scholarship, students must have 
        // an average grade between 71 and 87 of all attended classes.
        else if (studentAverageGrades < 87 && studentAverageGrades >= 71){
            update new Student__c(Id = studentId, Scholarship__c = 'Regular');
        }
        // In order to have increased scholarship, students must 
        // have an average grade higher than 88 of all attended classes.
        else if (studentAverageGrades >= 88){
            update new Student__c(Id = studentId, Scholarship__c = 'Increased');
        }    
    }

    public static void changeLectureStatus(List<Id> lectureIds, String status) {

        String newStatus;

        List<Lecture__c> lectures = new List<Lecture__c>();

        for (Id lectureId : lectureIds) {

            if (status == 'start') {
                newStatus = 'In progress';
            }
            else if (status == 'end') {
                newStatus = 'Is over';
            }

            lectures.add(new Lecture__c(Id = lectureId, Status__c = newStatus));
        }

        update lectures;
    }
}