force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Average_Grade__c.field-meta.xml
<CustomField>
    <fullName>Average_Grade__c</fullName>
    <description>Average grade among related enrollments.</description>
    <label>Average Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchoolDAOTest.cls
@isTest
private class SchoolDAOTest {
    
    @testSetup
    static void setup() {

        List<Student__c> testStudents = new List<Student__c>();
        List<Class__c> testClasses = new List<Class__c>();

        String yearOfStudy;

        // Creation of 5 classes and 5 students
        for(Integer i = 0; i < 5; i++) {

            testStudents.add(new Student__c(Name = ('TestStudent' + (i+1)), Average_Grade__c = (i+1) * 10));
            //testClasses.add(new Class__c(Year_of_Study__c = i));
        }

        insert testStudents;        
        insert testClasses;
    }

    @isTest
    static void testGetStudentPerformance() {

        Map<Id, Student__c> studentNames = new Map<Id, Student__c>([SELECT Name FROM Student__c]);
        Map<Id, Decimal> studentPerformance = SchoolDAO.getStudentPerformance(studentNames.keySet());

        for (Id studentId : studentNames.keySet()) {

            if (studentNames.get(studentId).Name == 'TestStudent1') {

                System.assertEquals(10, studentPerformance.get(studentId));
            }
            else if (studentNames.get(studentId).Name == 'TestStudent2') {

                System.assertEquals(20, studentPerformance.get(studentId));
            } 
            else if (studentNames.get(studentId).Name == 'TestStudent5') {
                System.assertEquals(50, studentPerformance.get(studentId));
            }
        }
    }
}