force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Year when class was studied</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SchoolServiceTest.cls
@isTest
private class SchoolServiceTest {

    @testSetup static void setup() {
        
        List<Student__c> testStudents = new List<Student__c>();
        List<Class__c> testClasses = new List<Class__c>();

        for (Integer i = 0; i < 2; i++) {

            testStudents.add(new Student__c(Name = 'TSt' + i));
            testClasses.add(new Class__c(Year__c = '999' + i));
        }

        insert testStudents;
        insert testClasses;  
    }
    
    @isTest static void testEnrollStudentToClass() {
        
        Student__c st = [SELECT Id FROM Student__c WHERE Name = 'TSt0' LIMIT 1];
        Class__c cl = [SELECT Id FROM Class__c WHERE Year__c = '9990' LIMIT 1];

        SchoolService.enrollStudentToClass(cl.Id, st.Id);
    }

    // recalculateScholarship(Id studentId)
    // setAcademicScholarship(Id studentId)
    // setGrade(Id classEnrollmentId, Integer grade)
    // setGrade(Id classId, Id studentId, Integer grade)
    // enrollStudentToClass(Id classId, Id studentId)
}