force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject of the class.</description>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Year when class was studied</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject of the class.</description>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics, Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClassesForStudentLWCComponent.cls
public class ClassesForStudentLWCComponent {
    
    @AuraEnabled(cacheable=true)
    public static List<ClassesForCurrentStudentWrapper> getClassesForCurrentStudent(Id studentId) {

        List<Class_Enrollment__c> classEnrollments = [
            SELECT Class__r.Year_of_Study__c, Class__r.Subject__c
            FROM Class_Enrollment__c 
            WHERE Student__r.Id = : studentId 
            AND Class__r.Year__c = :string.valueof(System.today().year())
            WITH SECURITY_ENFORCED
       ];   

       List<ClassesForCurrentStudentWrapper> wrapperList = new List<ClassesForCurrentStudentWrapper>();

       for (Class_Enrollment__c classEnrollment : classEnrollments) {

        ClassesForCurrentStudentWrapper wrapper = new ClassesForCurrentStudentWrapper(classEnrollment.Class__r.Year_of_Study__c,
            classEnrollment.Class__r.Subject__c);

        wrapperList.add(wrapper);
       }
       
       return wrapperList;
    }

    public class ClassesForCurrentStudentWrapper {
        
        @AuraEnabled
        public String yearOfStudy;
        
        @AuraEnabled
        public String subject;
        
        public ClassesForCurrentStudentWrapper(String yearOfStudy, String subject) {

            this.yearOfStudy = yearOfStudy;
            this.subject = subject;
        }
    }
}