force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <description>Estimation of student&apos;s efforts.</description>
    <label>Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentsInClassLWCComponent.cls
public class StudentsInClassLWCComponent {
    
    @AuraEnabled(cacheable=true)
    public static List<StudentsForCurrentClassWrapper> getStudentsForCurrentClass(Id classId) {

        List<Class_Enrollment__c> classEnrollments = [
            SELECT Student__r.Name, Grade__c
            FROM Class_Enrollment__c 
            WHERE Class__r.Id = : classId
            ];   
            
        List<StudentsForCurrentClassWrapper> wrapperList = new List<StudentsForCurrentClassWrapper>();
            
        for (Class_Enrollment__c classEnrollment : classEnrollments) {

            wrapperList.add(new StudentsForCurrentClassWrapper(classEnrollment.Student__r.Name, string.valueOf(classEnrollment.Grade__c)));
        }

       return wrapperList;
    }

    public class StudentsForCurrentClassWrapper {
        
        @AuraEnabled
        public String studentName;
        
        @AuraEnabled
        public String grade;
        
        public StudentsForCurrentClassWrapper(String studentName, String grade) {

            this.studentName = studentName;
            this.grade = grade;
        }
    }
}