force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClassEnrollmentHandlerTrigger.cls
public class ClassEnrollmentHandlerTrigger {

    public static void handleInsertion(List<Class_Enrollment__c> ClassEnrollments) {

        // preventing creation Class Enrollment if the Student's Year of Study is not one of the Class's Year of Study.
        exceptionByYearOfStudy(ClassEnrollments);

        // preventing creation more than one Class Enrollment for the same Class and Student
        exceptionByDuplicateStudents(ClassEnrollments);
    }

    public static void exceptionByYearOfStudy(List<Class_Enrollment__c> classEnrollments){

        Map<Id, Class__c> classesByYearOfStudy = new Map<Id, Class__c>([SELECT Year_Of_Study__c FROM Class__c]);
        Map<Id, Student__c> studentsByYearOfStudy = new Map<Id, Student__c>([SELECT Year_Of_Study__c FROM Student__c]);

        for (Class_Enrollment__c triggerClassEnrollment : classEnrollments) {

            if (classesByYearOfStudy.get(triggerClassEnrollment.Class__c).Year_Of_Study__c != studentsByYearOfStudy.get(triggerClassEnrollment.Student__c).Year_Of_Study__c){
                
                triggerClassEnrollment.addError('Year of study field on the student record does not match with the year of study field on the class record');
            }
        }
    }

    public static void exceptionByDuplicateStudents(List<Class_Enrollment__c> classEnrollments){

        Map<Id, Id> correspondingClassesAndStudents = new Map<Id, Id>();

        Map<Id, Class_Enrollment__c> existentClassEnrollments = new Map<Id, Class_Enrollment__c>(
            [SELECT 
                Class__c, Student__c
            FROM 
                Class_Enrollment__c
            ]);

        for (Class_Enrollment__c classEnrollment : classEnrollments) {

            if (correspondingClassesAndStudents.get(classEnrollment.Class__c) == NULL) {
                
                correspondingClassesAndStudents.put(classEnrollment.Class__c, classEnrollment.Student__c);
            } 
            else {

                classEnrollment.addError('Such a student already exists in such a class');
            }
        }

        for(Integer i = 0; i < classEnrollments.size(); i++) {
            
            Id classClEn_i_Id = classEnrollments.get(i).Class__c.Id;
            Id studentStEn_i_Id = classEnrollments.get(i).Student__c.Id;
            
            for(integer j = (i + 1); j < (classEnrollments.size() - 1); j++) {

                Id classClEn_j_Id = classEnrollments.get(j).Class__c.Id;
                Id studentStEn_j_Id = classEnrollments.get(j).Student__c.Id;

                if(classClEn_i_Id == classClEn_j_Id && studentStEn_i_Id == studentStEn_j_Id) {
                    
                    classEnrollments.remove(j);  
            }
        }
        
        for (Id currentClassId : correspondingClassesAndStudents.keySet()){

            Id currentStudentId = correspondingClassesAndStudents.get(currentClassId);

            if (existentClassEnrollments.get(currentClassId) != NULL && existentClassEnrollments.get(currentStudentId) != NULL) {
                
                classEnrollment.addError('Such a student already exists in such a class');
            }
        }
    }
}