force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <description>Estimation of student&apos;s efforts.</description>
    <label>Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Average_Grade__c.field-meta.xml
<CustomField>
    <fullName>Average_Grade__c</fullName>
    <description>Average grade among related enrollments.</description>
    <label>Average Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Scholarship__c.field-meta.xml
<CustomField>
    <fullName>Scholarship__c</fullName>
    <description>Type of the scholarship awarded to a student.</description>
    <label>Scholarship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Increased</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchoolServiceTest_new1.cls
@isTest
private class SchoolServiceTest_new1 {

    @testSetup static void setup() {
        
       Student__c student = new Student__c();
       Class__c testClass = new Class__c();
        
       insert student;
       insert testClass;
    }
    
    
    
    @isTest
    static void testEnrollStudent() {
        
        Student__c student = [
            SELECT
                Id, Average_Grade__c, Scholarship__c
            FROM
                Student__c
        ];
        
        Class__c testClass = [
            SELECT
                Id
            FROM 
                Class__c
        ];
        
        SchoolService.enrollStudentToClass(testClass.Id, student.Id);
        
        SchoolService.setGrade(testClass.Id, student.Id, 3);
        
        List<Class_Enrollment__c> classEnrollments = [
            SELECT
                Id, Grade__c
            FROM
                Class_Enrollment__c
        ];
        
        SchoolService.setAcademicScholarship(student.Id);
        
        student.Average_Grade__c = 80;
        
        update student;
        
        SchoolService.recalculateScholarship(student.Id);
        
        System.assertEquals(1, classEnrollments.size());
        
        System.assertEquals(3, classEnrollments.get(0).Grade__c);
        
        System.assertEquals('Regular', student.Scholarship__c);
        
    }

    @isTest
    static void testEnrollStudentToClass(){
        
        Student__c student = [
            SELECT
                Id, Average_Grade__c, Scholarship__c
            FROM
                Student__c
        ];
        
        Class__c testClass = [
            SELECT
                Id
            FROM 
                Class__c
        ];

        List<Class_Enrollment__c> classEnrollments = [
            SELECT
                Id, Grade__c
            FROM
                Class_Enrollment__c
        ];

        SchoolService.enrollStudentToClass(testClass.Id, student.Id);

        System.assertEquals(1, classEnrollments.size());
    }

    @isTest
    static void setGrade(){

        Student__c student = [
            SELECT
                Id, Average_Grade__c, Scholarship__c
            FROM
                Student__c
        ];
        
        Class__c testClass = [
            SELECT
                Id
            FROM 
                Class__c
        ];

        List<Class_Enrollment__c> classEnrollments = [
            SELECT
                Id, Grade__c
            FROM
                Class_Enrollment__c
        ];

        SchoolService.setGrade(testClass.Id, student.Id, 3);

        System.assertEquals(3, classEnrollments.get(0).Grade__c);
    }
}