force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Lecture_Subject__c.field-meta.xml
<CustomField>
    <fullName>Lecture_Subject__c</fullName>
    <label>Lecture Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Lecturer__c.field-meta.xml
<CustomField>
    <fullName>Lecturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lecturer</label>
    <referenceTo>Lecturer__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture_to_Class__c/Lecture_to_Class__c.object-meta.xml
<CustomObject>
    <label>Lecture to Class</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>Lecture to Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures to Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture_to_Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Lectures to Classes</relationshipLabel>
    <relationshipName>Lectures_to_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture_to_Class__c/fields/Lecture__c.field-meta.xml
<CustomField>
    <fullName>Lecture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lecture</label>
    <referenceTo>Lecture__c</referenceTo>
    <relationshipLabel>Lectures to Classes</relationshipLabel>
    <relationshipName>Lectures_to_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecturer__c/Lecturer__c.object-meta.xml
<CustomObject>
    <label>Lecturer</label>
    <nameField>
        <label>Lecturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lecturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LectureToClassHandlerTriggerTest.cls
@isTest
public class LectureToClassHandlerTriggerTest {
    
    @testSetup
    static void setup() {
        
        List<Lecture__c> testLectures = new List<Lecture__c>();
        List<Class__c> testClasses = new List<Class__c>();

        insert new Lecturer__c(Name = 'TestLecturer1');
        Id lecturerId = [SELECT Id FROM Lecturer__c].Id;

        for(Integer i = 0; i < 2; i++) {

            testLectures.add(new Lecture__c(Start_Date__c = datetime.newInstance(2024, 1, 1, 10, 30, 0), 
            Lecture_Subject__c = 'Algebra', Lecturer__c = lecturerId));
            testClasses.add(new Class__c(Year_of_Study__c = '1'));
        }

        insert testLectures;        
        insert testClasses;        
    }

    @isTest 
    static void testExceptionByDuplicateLectures() {

        List <Lecture__c> lectures = [SELECT Id FROM Lecture__c];
        List <Class__c> classes = [SELECT Id FROM Class__c];
    
        Boolean isFailed = false;
        
        try {
            
            Test.startTest();
            insert new Lecture_to_Class__c(Class__c = classes[0].Id, Lecture__c = lectures[0].Id);
            insert new Lecture_to_Class__c(Class__c = classes[0].Id, Lecture__c = lectures[0].Id);
            Test.stopTest();
        } 
        catch(DmlException e) {
    
            isFailed = true; 
        }
    
        System.assertEquals(true, isFailed);
    }
}