force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Series of lessons in a particular subject</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>The junction between Student and Class. Students can attend multiple classes, class can be attended by multiple students.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Indicates which class is attended.</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Indicates which student is attending the class.</description>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HttpCalloutClassEnrollmentTest.cls
@isTest
private class HttpCalloutClassEnrollmentTest {

    @TestSetup
    static void setup() {
        
        insert new Student__c( Name = 'TestName1', Year_of_Study__c = '1');
        insert new Class__c( Year_of_Study__c = '1');

        insert new Class_Enrollment__c( Student__c = [SELECT Id FROM Student__c LIMIT 1].Id, Class__c = [SELECT Id FROM Class__c LIMIT 1].Id );
    }

    @isTest static void testHttpCalloutClassEnrollment() {

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        HttpResponse res = HttpCalloutClassEnrollment.HttpCalloutClassEnrollment([SELECT Id FROM Class_Enrollment__c LIMIT 1].Id);
        Test.stopTest();

        System.assertEquals(200, res.getStatusCode());
    }

    @isTest static void testHttpCalloutDeletingClassEnrollment_StatusCode200() {

        List <Class_Enrollment__c> classEnrollments = [SELECT Id FROM Class_Enrollment__c];

        Test.startTest();
        HttpCalloutClassEnrollment.HttpCalloutDeletingClassEnrollment(200, classEnrollments[0].Id);
        Test.stopTest();

        List <Class_Enrollment__c> classEnrollmentsToCheck = [SELECT Id FROM Class_Enrollment__c];

        System.assertEquals(0, classEnrollmentsToCheck.size());
    }
}