force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Lecture_Subject__c.field-meta.xml
<CustomField>
    <fullName>Lecture_Subject__c</fullName>
    <label>Lecture Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Lecturer__c.field-meta.xml
<CustomField>
    <fullName>Lecturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lecturer</label>
    <referenceTo>Lecturer__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecturer__c/Lecturer__c.object-meta.xml
<CustomObject>
    <label>Lecturer</label>
    <nameField>
        <label>Lecturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lecturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LectureHandlerTriggerTest.cls
@isTest
private class LectureHandlerTriggerTest {
    
    @isTest
    public static void testAddEndDate() {

        Test.startTest();
        insert new Lecture__c(
            Start_Date__c = datetime.newInstance(2021, 1, 1, 10, 30, 0), 
            Lecture_Subject__c = 'Algebra', Lecturer__c = 'TestLecturere1');

        Datetime lectureEndDatetime = [SELECT End_Date__c FROM Lecture__c].End_Date__c;

        Datetime datetimeToCheck = datetime.newInstance(2021, 1, 1, 12, 0, 0);
        Test.stopTest();

        System.assertEquals(datetimeToCheck, lectureEndDatetime);
    }
}