force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Lecture_Subject__c.field-meta.xml
<CustomField>
    <fullName>Lecture_Subject__c</fullName>
    <label>Lecture Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Lecturer__c.field-meta.xml
<CustomField>
    <fullName>Lecturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lecturer</label>
    <referenceTo>Lecturer__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecturer__c/Lecturer__c.object-meta.xml
<CustomObject>
    <label>Lecturer</label>
    <nameField>
        <label>Lecturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lecturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecturer__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Statistics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Physics (Advanced)</fullName>
            </value>
            <value>
                <fullName>Economics</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>World History</fullName>
            </value>
            <value>
                <fullName>English Language</fullName>
            </value>
            <value>
                <fullName>German Language</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LectureHandlerTrigger.cls
public class LectureHandlerTrigger {
    
    public static void handleBeforeInsertion(List<Lecture__c> lectures) {
        
        // preventing creation lecture, when lecturer and lecture subject does not match
        exceptionBySubject(lectures);

        // Adding 1.5 hours to the start date to make end date if was blanc
        addEndDate(lectures);
    }

    public static void addEndDate(List<Lecture__c> lectures) {

        for (Lecture__c lecture : lectures) {

            if (lecture.End_Date__c == NULL) {

                lecture.End_Date__c = lecture.Start_Date__c.addMinutes(90);
            }
        }
    }

    public static void exceptionBySubject(List<Lecture__c> lectures) {

        Set<Id> lecturerIds = new Set<Id>();

        for (Lecture__c lecture : lectures) {

            lecturerIds.add(lecture.Lecturer__c);
        }

        Map<Id, Lecturer__c> lecturers = new Map<Id, Lecturer__c>([SELECT Id, Subject__c FROM Lecturer__c WHERE Id IN :lecturerIds]);

        

        for (Lecture__c lecture : lectures) {

            if (!lecturers.get(lecture.Lecturer__c).Subject__c.contains(lecture.Lecture_Subject__c)) {

                lecture.addError('The subject for lecturer and lecture does not match');
            }
        }
    }
}