force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lecture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture_to_Class__c/Lecture_to_Class__c.object-meta.xml
<CustomObject>
    <label>Lecture to Class</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>Lecture to Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lectures to Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture_to_Class__c/fields/Lecture__c.field-meta.xml
<CustomField>
    <fullName>Lecture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lecture</label>
    <referenceTo>Lecture__c</referenceTo>
    <relationshipLabel>Lectures to Classes</relationshipLabel>
    <relationshipName>Lectures_to_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LectureToClassHandlerTrigger.cls
public class LectureToClassHandlerTrigger {
    
    public static void handleInsertion(List<Lecture_to_Class__c> lecturesToClasses) {

        exceptionByInOneTimeLectures(lecturesToClasses);
    }

    public static void exceptionByInOneTimeLectures(List<Lecture_to_Class__c> lecturesToClasses) {

        List <Id> lecturesId = new List<Id>();
        System.debug('L to C input: ' + lecturesToClasses[0]);
        System.debug('L id: ' + lecturesToClasses[0].Lecture__r.Id);

        for (Lecture_to_Class__c l : lecturesToClasses) {
            
            lecturesId.add(l.Lecture__r.Id);
        }

        System.debug('lectures id: ' + lecturesId);

        List<Lecture__c> lectures = [SELECT Id FROM Lecture__c WHERE Start_Date__c > :Datetime.now() AND Id NOT IN :lecturesId];

        System.debug('lectures: ' + lectures);

        // for (Lecture_to_Class__c lectureToClass : lecturesToClasses) {

        //     for (Lecture__c lecture : lectures) {

        //         if (lectureToClass.Lecture__r.Start_Date__c >= lecture.Start_Date__c && lectureToClass.Lecture__r.Start_Date__c < lecture.End_Date__c 
        //         && lectureToClass.Lecture__r.End_Date__c > lecture.Start_Date__c && lectureToClass.Lecture__r.End_Date__c < lecture.End_Date__c) {

        //             lectureToClass.addError('erora nahyi');
        //         }
        //     }
        // }
    }
}