force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Scholarship__c.field-meta.xml
<CustomField>
    <fullName>Scholarship__c</fullName>
    <description>Type of the scholarship awarded to a student.</description>
    <label>Scholarship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Increased</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Scholarship_Rate__c.field-meta.xml
<CustomField>
    <fullName>Scholarship_Rate__c</fullName>
    <label>Scholarship Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScholarshipRateBatch.cls
public class ScholarshipRateBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {

        String scholarshipQuery = 'SELECT Scholarship__c FROM Student__c';
        
        return Database.getQueryLocator( scholarshipQuery );
    }

    public void execute(Database.BatchableContext bc, List<Student__c> scope) {

        for (Student__c c : scope) {

            if (c.Scholarship__c == 'Unassigned' || c.Scholarship__c == NULL) { c.Scholarship_Rate__c = 0; }
            else if (c.Scholarship__c == 'Regular') { c.Scholarship_Rate__c = 100; }
            else if (c.Scholarship__c == 'Increased') { c.Scholarship_Rate__c = 125; }
            else if (c.Scholarship__c == 'Academic') { c.Scholarship_Rate__c = 150; }
        }

        update scope;
    }

    public void finish(Database.BatchableContext bc) {}
}