force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Average_Grade__c.field-meta.xml
<CustomField>
    <fullName>Average_Grade__c</fullName>
    <description>Average grade among related enrollments.</description>
    <label>Average Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentRestResource.cls
@RestResource(urlMapping='/*')
global class StudentRestResource {
    
    @HttpGet
    global static List<Student__c> getTopStudents() {
        
        // return JSON.serialize(new List<Student__c>([SELECT Id, Name, Average_Grade__c FROM Student__c ORDER By Average_Grade__c ASC LIMIT 5]));
        return new List<Student__c>([SELECT Id, Name, Average_Grade__c FROM Student__c ORDER BY Average_Grade__c DESC NULLS LAST LIMIT 5]);
    }
}