force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Year_of_Study__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Study__c</fullName>
    <label>Year of Study</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnrollStudentToNextYearBatch.cls
public class EnrollStudentToNextYearBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {

        String lastYear = '5';
        String scholarshipQuery = 'SELECT Year_of_Study__c FROM Student__c WHERE Year_of_Study__c != :lastYear';
        
        return Database.getQueryLocator( scholarshipQuery );
    }

    public void execute(Database.BatchableContext bc, List<Student__c> scope) {

        for (Student__c c : scope) {

            c.Year_of_Study__c = string.valueof(integer.valueof(c.Year_of_Study__c) + 1);
        }

        update scope;
    }

    public void finish(Database.BatchableContext bc) {


    }
}