force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Average_Grade__c.field-meta.xml
<CustomField>
    <fullName>Average_Grade__c</fullName>
    <description>Average grade among related enrollments.</description>
    <label>Average Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SchoolDAO.cls
public class SchoolDAO {

    public static Map<Id, Decimal> getStudentPerformance(Set<Id> studentIds) {

        // Ініціалізація мапки, для збереження ідшки і оцінки
        Map<Id, Decimal> studentAverageGrades = new Map<Id, Decimal>();    

        // Ініціалізація ліста, в який кверяєм значення ідшки і середньої оцінки для студентів, ідшки яких є в сеті
        List<Student__c> students = [SELECT Id, Average_Grade__c FROM Student__c WHERE Id IN :studentIds]; 

        // Цикл перевірки кожного студента з ліста
        for (Student__c st : students){
            studentAverageGrades.put(st.Id, st.Average_Grade__c); // put значень в порожню мапку
        }

        return studentAverageGrades;    
    }
}