force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person who is studying at school.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Scholarship__c.field-meta.xml
<CustomField>
    <fullName>Scholarship__c</fullName>
    <description>Type of the scholarship awarded to a student.</description>
    <label>Scholarship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Increased</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentAuraControllerTest.cls
@isTest
private class StudentAuraControllerTest {
    
    @testSetup
    static void setup() {
        
        List<Student__c> testStudents = new List<Student__c>();

        testStudents.add(new Student__c(Name = 'TestStudent1', Scholarship__c = 'Unassigned'));
        testStudents.add(new Student__c(Name = 'TestStudent2', Scholarship__c = 'Regular'));
        testStudents.add(new Student__c(Name = 'TestStudent3', Scholarship__c = 'Increased'));
        testStudents.add(new Student__c(Name = 'TestStudent4'));

        insert testStudents;        
    }

    @isTest
    static void testGetStudentsWithScholarship() {

        Test.startTest();
        List<Student__c> studentsWithScholarship = StudentAuraController.getStudentsWithScholarship();
        Test.stopTest();

        System.assertEquals(2, studentsWithScholarship.size());

        for (Student__c currentStudent : studentsWithScholarship) {

            if (currentStudent.Name == 'TestStudent2') {

                System.assertEquals('Regular', currentStudent.Scholarship__c);
            }
            else if (currentStudent.Name == 'TestStudent3') {

                System.assertEquals('Increased', currentStudent.Scholarship__c);
            }
        }      
    }
}